modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Infinite%20Trading"
logoFile="icon.png"

[[mods]]
modId="infinitetrading"
version="4.0"
displayName="Infinite Trading"
displayURL="https://curseforge.com/minecraft/mc-mods/infinite-trading"
authors="Rick South"
description='''Prevents villager and wandering trader trades from locking up, making them be always available.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.infinitetrading]]
    modId="collective"
    mandatory=true
    versionRange="[6.17,)"
    ordering="NONE"
    side="BOTH"