modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Infinite%20Trading"
logoFile="icon.png"

[[mods]]
modId="infinitetrading"
version="4.4"
displayName="Infinite Trading"
displayURL="https://serilum.com/mod/infinite-trading"
authors="Rick South"
description='''Prevents villager and wandering trader trades from locking up, making them be always available.
If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jeremy Langford, Michael W. S., Shana Gitnick, Sukhmai, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.infinitetrading]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.infinitetrading]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"