modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Infinite%20Trading"
logoFile="icon.png"

[[mods]]
modId="infinitetrading"
version="4.5"
displayName="Infinite Trading"
displayURL="https://serilum.com/mod/infinite-trading"
authors="Rick South"
description='''Prevents villager and wandering trader trades from locking up, making them be always available.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.infinitetrading]]
    modId="collective"
    type="required"
    versionRange="[7.86,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.infinitetrading]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "infinitetrading.mixins.json"